EXP_NAME: 'ROTATION_1'
RNG_SEED: 1
GPU_ID: '3'
DATASET:
  NAME: TINYIMAGENET 
  ROOT_DIR: '/DATA1/akshay/datasets/tiny-imagenet-200/'
  VAL_RATIO: 0.1
  AUG_METHOD: 'horizontalflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 4
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.1
  LR_POLICY: steps
  LR_MULT: 0.2
  STEPS: [0, 30, 60, 80] #[0, 30, 60, 90]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
  EVAL_PERIOD: 5
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True