# EXP_NAME: 'VAE_Testing'
RNG_SEED: 1
GPU_ID: '3'
SWEEP: False
DATASET:
  NAME: TINYIMAGENET
  ROOT_DIR: '/DATA/akshay/datasets/tiny-imagenet-200/'
  VAL_RATIO: 0.05
  AUG_METHOD: 'none'
OPTIM:
  TYPE: 'adam'
  BASE_LR: 0.001
  LR_POLICY: none
  LR_MULT: 0.2
  STEPS: [0, 60, 120, 160, 200] #[0, 30, 60, 90]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 200
  IM_SIZE: 64
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True