# EXP_NAME: 'SOME'
RNG_SEED: 1
GPU_ID: '3'
SWEEP: False
DATASET:
  NAME: MNIST 
  ROOT_DIR: './data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'adam'
  BASE_LR: 0.005
  LR_POLICY: none
  LR_MULT: 0.1
  # STEPS: [0, 60, 120, 160, 200] 
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 64
  IM_SIZE: 32
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
INIT_POOL:
  INIT_RATIO: 0.001
  # SAMPLING_FN: scan
ACTIVE_LEARNING:
  BUDGET_SIZE: 60
  # SAMPLING_FN: 'uncertainty'
  MAX_ITER: 10
  DROPOUT_ITERATIONS: 25